#!/bin/bash

R="\e[31m"
G="\e[32m"
N="\e[0m"
Y="\e[33m"

SOURCE_DIR=/tmp/shellscript-logs

if [ ! -d $SOURCE_DIR ]
then 
    echo -e "$R source directory $SOURCE_DIR not exist $N"
fi

FILESTODELETE=$(find $SOURCE_DIR -type f -mtime +14 -name "*.log" )

while IFS= read -r line
do
    echo "Deleting Files $line"
    rm -rf $line
done <<< $FILESTODELETE